# Generated by Django 5.0 on 2023-12-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neobis_challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
