# Generated by Django 5.0 on 2023-12-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neobis_challenge', '0005_cart_cartitem_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True, unique=True),
        ),
    ]
